#pragma once

#define VERTEX_ATTRIB_NUM 4

extern const char* VERTEX_ATTRIB_NAMES[VERTEX_ATTRIB_NUM];

extern const int VERTEX_ATTRIB_FLOAT_COUNT[VERTEX_ATTRIB_NUM];

#define STENCIL_VALUE_SKYBOX 0x01
#define STENCIL_VALUE_LIT 0x02
